setGeneric("DegreePathmutscore", function(obj, ...)standardGeneric("DegreePathmutscore"))
setGeneric("ConsensusCluster", function(obj, ...)standardGeneric("ConsensusCluster"))
setGeneric("calculate_ICI", function(obj, ...)standardGeneric("calculate_ICI"))
setGeneric("Hclust", function(obj, ...)standardGeneric("Hclust"))
setGeneric("SelectBestClusterNum", function(obj,...)standardGeneric("SelectBestClusterNum"))
setGeneric("NetFeatureCalculate", function(obj, ...)standardGeneric("NetFeatureCalculate"))
setGeneric("plot_mut_classification", function(obj, ...)standardGeneric("plot_mut_classification"))
setGeneric("plot_mut_distribution", function(obj, ...)standardGeneric("plot_mut_distribution"))
setGeneric("mut_enrich", function(obj, ...)standardGeneric("mut_enrich"))
setGeneric("plot_point_samllworld", function(obj, ...)standardGeneric("plot_point_samllworld"))
setGeneric("plot_point_fetsig", function(obj, ...)standardGeneric("plot_point_fetsig"))
